# Generated by Django 5.2.1 on 2025-10-16 09:58

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyGroup",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "study_groups",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("star_rating", models.PositiveSmallIntegerField()),
                ("content", models.CharField(max_length=300)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "study_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="studies.studygroup"
                    ),
                ),
            ],
            options={
                "db_table": "reviews",
                "indexes": [
                    models.Index(fields=["study_group", "-created_at"], name="ix_reviews_group_created_desc"),
                    models.Index(fields=["user", "-created_at"], name="ix_reviews_user_created_desc"),
                    models.Index(fields=["is_public"], name="ix_reviews_public"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("user", "study_group"), name="uq_reviews_user_group"),
                    models.CheckConstraint(
                        condition=models.Q(("star_rating__gte", 1), ("star_rating__lte", 5)),
                        name="ck_reviews+star_rating_1_5",
                    ),
                ],
            },
        ),
    ]
