# Generated by Django 5.2.1 on 2025-10-17 10:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lecture", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="", max_length=20)),
                ("introduction", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "max_headcount",
                    models.PositiveSmallIntegerField(
                        default=2,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("profile_img_url", models.CharField(blank=True, max_length=255, null=True)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "대기중"), ("ONGOING", "진행중"), ("ENDED", "종료됨")],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "db_table": "study_groups",
            },
        ),
        migrations.CreateModel(
            name="GroupMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_leader", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "study_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="members", to="studies.studygroup"
                    ),
                ),
            ],
            options={
                "db_table": "group_members",
            },
        ),
        migrations.CreateModel(
            name="GroupSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(default="", max_length=255)),
                ("objective", models.CharField(default="", max_length=255)),
                ("session_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "study_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="schedules", to="studies.studygroup"
                    ),
                ),
            ],
            options={
                "db_table": "group_schedules",
            },
        ),
        migrations.CreateModel(
            name="StudyLecture",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_links",
                        to="lecture.crawledlecture",
                    ),
                ),
                (
                    "study_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="lectures", to="studies.studygroup"
                    ),
                ),
            ],
            options={
                "db_table": "study_lectures",
            },
        ),
        migrations.CreateModel(
            name="ScheduleParticipant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="schedules", to="studies.groupmember"
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="studies.groupschedule",
                    ),
                ),
            ],
            options={
                "db_table": "schedule_participants",
                "constraints": [
                    models.UniqueConstraint(fields=("schedule", "member"), name="unique_participant_per_schedule")
                ],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "star_rating",
                    models.CharField(
                        choices=[
                            ("5_OUT_OF_5_STARS", "5점"),
                            ("4_OUT_OF_5_STARS", "4점"),
                            ("3_OUT_OF_5_STARS", "3점"),
                            ("2_OUT_OF_5_STARS", "2점"),
                            ("1_OUT_OF_5_STARS", "1점"),
                        ],
                        default="5_OUT_OF_5_STARS",
                        max_length=20,
                    ),
                ),
                ("content", models.CharField(max_length=300)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "study_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="studies.studygroup"
                    ),
                ),
            ],
            options={
                "db_table": "reviews",
                "indexes": [
                    models.Index(fields=["study_group", "-created_at"], name="ix_reviews_group_created_desc"),
                    models.Index(fields=["user", "-created_at"], name="ix_reviews_user_created_desc"),
                ],
                "constraints": [models.UniqueConstraint(fields=("user", "study_group"), name="uq_reviews_user_group")],
            },
        ),
        migrations.AddConstraint(
            model_name="groupschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_time__gt", models.F("start_time"))), name="valid_schedule_time_range"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="groupmember",
            unique_together={("study_group", "user_id")},
        ),
        migrations.AddConstraint(
            model_name="studylecture",
            constraint=models.UniqueConstraint(fields=("lecture", "study_group"), name="unique_lecture_per_group"),
        ),
    ]
