# Generated by Django 5.2.1 on 2025-10-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
