# Generated by Django 5.2.1 on 2025-10-16 07:25

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="studygroup",
            old_name="image",
            new_name="profile_img_url",
        ),
        migrations.RemoveField(
            model_name="studygroup",
            name="description",
        ),
        migrations.RemoveField(
            model_name="studygroup",
            name="leader",
        ),
        migrations.RemoveField(
            model_name="studygroup",
            name="lecture_ids",
        ),
        migrations.RemoveField(
            model_name="studygroup",
            name="max_members",
        ),
        migrations.AddField(
            model_name="studygroup",
            name="introduction",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="studygroup",
            name="max_headcount",
            field=models.PositiveSmallIntegerField(
                default=10,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AddField(
            model_name="studygroup",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="studygroup",
            name="end_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="studygroup",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="studygroup",
            name="name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="studygroup",
            name="start_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="studygroup",
            name="status",
            field=models.CharField(
                choices=[("PENDING", "대기중"), ("ONGOING", "진행중"), ("ENDED", "종료됨")],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="studygroup",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterModelTable(
            name="studygroup",
            table="study_groups",
        ),
        migrations.CreateModel(
            name="GroupMember",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.BigIntegerField()),
                ("is_leader", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "study_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="members", to="studies.studygroup"
                    ),
                ),
            ],
            options={
                "db_table": "group_members",
                "unique_together": {("study_group", "user_id")},
            },
        ),
        migrations.CreateModel(
            name="GroupSchedule",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("objective", models.CharField(max_length=255)),
                ("session_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "study_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="schedules", to="studies.studygroup"
                    ),
                ),
            ],
            options={
                "db_table": "group_schedules",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("star_rating", models.PositiveSmallIntegerField()),
                ("content", models.CharField(max_length=300)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "study_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="studies", to="studies.studygroup"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="studies", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "studies",
            },
        ),
        migrations.CreateModel(
            name="ScheduleParticipant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="schedules", to="studies.groupmember"
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="studies.groupschedule",
                    ),
                ),
            ],
            options={
                "db_table": "schedule_participants",
            },
        ),
        migrations.CreateModel(
            name="StudyLecture",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("lecture_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "study_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="lectures", to="studies.studygroup"
                    ),
                ),
            ],
            options={
                "db_table": "study_lectures",
            },
        ),
        migrations.DeleteModel(
            name="StudyMember",
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["study_group", "-created_at"], name="ix_reviews_group_created_desc"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["user", "-created_at"], name="ix_reviews_user_created_desc"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["is_public"], name="ix_reviews_public"),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(fields=("user", "study_group"), name="uq_reviews_user_group"),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.CheckConstraint(
                condition=models.Q(("star_rating__gte", 1), ("star_rating__lte", 5)), name="ck_reviews+star_rating_1_5"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="scheduleparticipant",
            unique_together={("schedule", "member")},
        ),
        migrations.AlterUniqueTogether(
            name="studylecture",
            unique_together={("lecture_id", "study_group")},
        ),
    ]
