# Generated by Django 5.2.1 on 2025-10-17 02:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupmember",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="groupmember",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="groupmember",
            name="user_id",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="groupschedule",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="groupschedule",
            name="objective",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="groupschedule",
            name="title",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="groupschedule",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="scheduleparticipant",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="studygroup",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="studygroup",
            name="introduction",
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="studygroup",
            name="max_headcount",
            field=models.PositiveSmallIntegerField(
                default=2,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="studygroup",
            name="name",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="studygroup",
            name="profile_img_url",
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="studygroup",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="studylecture",
            name="lecture_id",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="studylecture",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("star_rating", models.PositiveSmallIntegerField()),
                ("content", models.CharField(max_length=300)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "study_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="studies.studygroup"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "reviews",
                "indexes": [
                    models.Index(fields=["study_group", "-created_at"], name="ix_reviews_group_created_desc"),
                    models.Index(fields=["user", "-created_at"], name="ix_reviews_user_created_desc"),
                    models.Index(fields=["is_public"], name="ix_reviews_public"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("user", "study_group"), name="uq_reviews_user_group"),
                    models.CheckConstraint(
                        condition=models.Q(("star_rating__gte", 1), ("star_rating__lte", 5)),
                        name="ck_reviews+star_rating_1_5",
                    ),
                ],
            },
        ),
    ]
