# Generated by Django 5.2.1 on 2025-11-03 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0002_groupmember_uuid_groupschedule_uuid_review_uuid_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="groupschedule",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AlterField(
            model_name="groupschedule",
            name="end_time",
            field=models.TimeField(help_text="스터디 종료 시간 (HH:MM)"),
        ),
        migrations.AlterField(
            model_name="groupschedule",
            name="objective",
            field=models.CharField(default="", help_text="스터디 목표 (필수)", max_length=255),
        ),
        migrations.AlterField(
            model_name="groupschedule",
            name="session_date",
            field=models.DateField(help_text="스터디 진행일 (YYYY-MM-DD)"),
        ),
        migrations.AlterField(
            model_name="groupschedule",
            name="start_time",
            field=models.TimeField(help_text="스터디 시작 시간 (HH:MM)"),
        ),
        migrations.AlterField(
            model_name="groupschedule",
            name="study_group",
            field=models.ForeignKey(
                help_text="해당 일정이 속한 스터디 그룹",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="studies.studygroup",
            ),
        ),
        migrations.AlterField(
            model_name="groupschedule",
            name="title",
            field=models.CharField(default="", help_text="스터디 일정 제목 (필수)", max_length=255),
        ),
        migrations.AlterField(
            model_name="scheduleparticipant",
            name="member",
            field=models.ForeignKey(
                help_text="스케줄에 참가하는 그룹 멤버 (FK)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="studies.groupmember",
            ),
        ),
        migrations.AlterField(
            model_name="scheduleparticipant",
            name="schedule",
            field=models.ForeignKey(
                help_text="어떤 스케줄에 속하는지 (FK)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="studies.groupschedule",
            ),
        ),
        migrations.AddIndex(
            model_name="groupschedule",
            index=models.Index(fields=["study_group", "session_date"], name="idx_by_group_date"),
        ),
        migrations.AddIndex(
            model_name="groupschedule",
            index=models.Index(fields=["session_date", "-created_at"], name="idx_by_date_created_desc"),
        ),
        migrations.AddIndex(
            model_name="scheduleparticipant",
            index=models.Index(fields=["schedule"], name="idx_by_schedule"),
        ),
        migrations.AddIndex(
            model_name="scheduleparticipant",
            index=models.Index(fields=["member"], name="idx_by_member"),
        ),
    ]
