# Generated by Django 5.2.7 on 2025-11-03 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0003_alter_groupschedule_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("ai_summary", models.TextField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "study_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="notes", to="studies.studygroup"
                    ),
                ),
            ],
            options={
                "db_table": "study_notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudyNoteAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file_url", models.CharField(max_length=255)),
                ("file_name", models.CharField(max_length=255)),
                (
                    "study_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="studies.studynote"
                    ),
                ),
            ],
            options={
                "db_table": "study_note_attachments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudyNoteImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("img_url", models.CharField(max_length=255)),
                (
                    "study_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="images", to="studies.studynote"
                    ),
                ),
            ],
            options={
                "db_table": "study_note_images",
                "ordering": ["-created_at"],
            },
        ),
    ]
