# Generated by Django 5.2.7 on 2025-11-04 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecture", "0003_alter_crawledlecture_unique_together"),
        ("studies", "0004_studynote_studynoteattachment_studynoteimage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="studygroup",
            name="lectures",
            field=models.ManyToManyField(
                related_name="study_groups", through="studies.StudyLecture", to="lecture.crawledlecture"
            ),
        ),
        migrations.AddField(
            model_name="studygroup",
            name="members",
            field=models.ManyToManyField(
                related_name="study_groups", through="studies.GroupMember", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="groupmember",
            name="study_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="group_members", to="studies.studygroup"
            ),
        ),
        migrations.AlterField(
            model_name="studylecture",
            name="lecture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="study_lectures", to="lecture.crawledlecture"
            ),
        ),
        migrations.AlterField(
            model_name="studylecture",
            name="study_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="study_lectures", to="studies.studygroup"
            ),
        ),
    ]
