# Generated by Django 5.2.7 on 2025-11-13 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0006_alter_studynote_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupschedule",
            name="participants",
            field=models.ManyToManyField(
                related_name="study_schedules", through="studies.ScheduleParticipant", to="studies.groupmember"
            ),
        ),
        migrations.AlterField(
            model_name="scheduleparticipant",
            name="member",
            field=models.ForeignKey(
                help_text="스케줄에 참가하는 그룹 멤버 (FK)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_participants",
                to="studies.groupmember",
            ),
        ),
        migrations.AlterField(
            model_name="scheduleparticipant",
            name="schedule",
            field=models.ForeignKey(
                help_text="어떤 스케줄에 속하는지 (FK)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_participants",
                to="studies.groupschedule",
            ),
        ),
    ]
