# Generated by Django 5.2.1 on 2025-10-17 09:16

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.users.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=30)),
                ("nickname", models.CharField(max_length=10, unique=True)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=20, unique=True, validators=[apps.users.validators.validate_korean_phone]
                    ),
                ),
                ("gender", models.CharField(choices=[("M", "남성"), ("F", "여성")], max_length=6)),
                ("birthday", models.DateField()),
                ("profile_img_url", models.URLField(blank=True, max_length=255, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Withdrawal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("NO_LONGER_NEEDED", "서비스 이용할 시간이 없음"),
                            ("LACK_OF_INTEREST", "관심이 사라짐"),
                            ("TOO_DIFFICULT", "서비스를 이용하기가 너무 어려움"),
                            ("FOUND_BETTER_SERVICE", "더 좋은 대안을 찾음"),
                            ("PRIVACY_CONCERNS", "개인정보/보안 우려"),
                            ("POOR_SERVICE_QUALITY", "서비스 품질 불만"),
                            ("TECHNICAL_ISSUES", "기술적 문제(버그 등)"),
                            ("LACK_OF_CONTENT", "원하는 콘텐츠나 기능의 부족"),
                            ("OTHER", "기타"),
                        ],
                        max_length=50,
                        verbose_name="탈퇴 사유",
                    ),
                ),
                ("reason_detail", models.CharField(max_length=500, verbose_name="구체적인 탈퇴 사유")),
                ("due_date", models.DateField(verbose_name="계정 삭제 예정일")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="withdrawals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "withdrawals",
            },
        ),
        migrations.CreateModel(
            name="SocialUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[("google", "Google"), ("kakao", "Kakao"), ("naver", "Naver")],
                        help_text="소셜 로그인 제공 업체",
                        max_length=20,
                    ),
                ),
                ("provider_id", models.CharField(help_text="소셜로그인 제공 업체에서 주는 고유 id", max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="socials", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "social_users",
                "constraints": [
                    models.UniqueConstraint(fields=("user", "provider"), name="uq_user_provider_one"),
                    models.UniqueConstraint(fields=("provider", "provider_id"), name="uq_provider_uid"),
                ],
            },
        ),
    ]
