# Generated by Django 5.2.1 on 2025-10-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_uuid"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="withdrawal",
            index=models.Index(fields=["due_date"], name="idx_withdrawals_due_date"),
        ),
        migrations.AddIndex(
            model_name="withdrawal",
            index=models.Index(fields=["user_id"], name="idx_withdrawals_user_id"),
        ),
    ]
