# Generated by Django 5.2.7 on 2025-11-10 04:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_withdrawal_idx_withdrawals_due_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialuser",
            name="provider",
            field=models.CharField(
                choices=[("kakao", "Kakao"), ("naver", "Naver")], help_text="소셜 로그인 제공 업체", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_img_url",
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
