# Generated by Django 5.2.7 on 2025-11-14 04:43

import apps.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_socialuser_provider_alter_user_profile_img_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=20, null=True, unique=True, validators=[apps.users.validators.validate_korean_phone]
            ),
        ),
    ]
