# Generated by Django 5.2.1 on 2025-10-27 08:04

import apps.recruitments.models.recruitments
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("studies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Recruitment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("title", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("estimated_fee", models.IntegerField()),
                (
                    "expected_headcount",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("close_at", models.DateTimeField(default=apps.recruitments.models.recruitments.default_close_at)),
                ("is_closed", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruitments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "study_group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruitments",
                        to="studies.studygroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RecruitmentAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file_url", models.CharField(max_length=255, unique=True)),
                ("file_name", models.CharField(max_length=50)),
                (
                    "recruitment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="recruitments.recruitment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RecruitmentImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("img_url", models.URLField()),
                (
                    "recruitment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="recruitments.recruitment",
                    ),
                ),
            ],
            options={
                "verbose_name": "공고 이미지",
                "verbose_name_plural": "공고 이미지 목록",
                "db_table": "recruitment_images",
            },
        ),
        migrations.CreateModel(
            name="RecruitmentTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recruitment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruitment_tags",
                        to="recruitments.recruitment",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruitment_tags",
                        to="recruitments.tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "공고 태그 연결",
                "verbose_name_plural": "공고 태그 연결 목록",
                "db_table": "recruitments_recruitment_tag",
            },
        ),
        migrations.AddField(
            model_name="recruitment",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="recruitments", through="recruitments.RecruitmentTag", to="recruitments.tag"
            ),
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "user_id", "recruitment_id", blank=True, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recruitment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="recruitments.recruitment",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user", "-created_at"], name="recruitment_user_id_724686_idx"),
                    models.Index(fields=["recruitment", "-created_at"], name="recruitment_recruit_8cc2de_idx"),
                ],
                "unique_together": {("user", "recruitment")},
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("self_introduction", models.TextField()),
                ("motivation", models.TextField()),
                ("objective", models.CharField(max_length=300)),
                ("available_time", models.CharField(max_length=200)),
                ("has_study_experience", models.BooleanField(default=False)),
                ("study_experience", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("APPLIED", "지원"),
                            ("APPROVED", "승인"),
                            ("REJECTED", "거절"),
                            ("WITHDRAWN", "취소"),
                        ],
                        default="APPLIED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recruitment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="recruitments.recruitment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recruitment", "status", "-created_at"], name="recruitment_recruit_fd2627_idx"
                    ),
                    models.Index(fields=["user", "-created_at"], name="recruitment_user_id_0faa3b_idx"),
                ],
                "unique_together": {("recruitment", "user")},
            },
        ),
        migrations.CreateModel(
            name="SearchLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("q", models.CharField(max_length=255)),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("results_count", models.IntegerField(default=0)),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["-created_at"], name="recruitment_created_a3908c_idx"),
                    models.Index(fields=["q"], name="recruitment_q_a18817_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="recruitmenttag",
            constraint=models.UniqueConstraint(fields=("recruitment", "tag"), name="unique_recruitment_tag"),
        ),
    ]
