# Generated by Django 5.2.1 on 2025-10-20 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitments", "0001_initial"),
        ("studies", "0002_delete_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruitment",
            name="study_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recruitments",
                to="studies.studygroup",
            ),
        ),
    ]
