# Generated by Django 5.2.1 on 2025-10-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[("APPLIED", "지원"), ("APPROVED", "승인"), ("REJECTED", "거절"), ("WITHDRAWN", "취소")],
                default="APPLIED",
                max_length=20,
            ),
        ),
    ]
