# Generated by Django 5.2.1 on 2025-10-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitments", "0002_recruitment_study_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recruitmenttag",
            name="id",
        ),
        migrations.AddField(
            model_name="recruitmenttag",
            name="pk",
            field=models.CompositePrimaryKey(
                "tag_id", "recruitment_id", blank=True, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
