# Generated by Django 5.2.1 on 2025-10-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitments", "0002_alter_application_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookmark",
            name="id",
        ),
        migrations.AddField(
            model_name="bookmark",
            name="pk",
            field=models.CompositePrimaryKey(
                "user_id", "recruitment_id", blank=True, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
