# Generated by Django 5.2.1 on 2025-10-29 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitments", "0003_remove_bookmark_id_bookmark_pk"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="recruitmenttag",
            name="unique_recruitment_tag",
        ),
        migrations.AddField(
            model_name="recruitment",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="recruitments", through="recruitments.RecruitmentTag", to="recruitments.tag"
            ),
        ),
        migrations.AlterField(
            model_name="recruitmenttag",
            name="recruitment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recruitment_tags",
                to="recruitments.recruitment",
            ),
        ),
        migrations.AlterField(
            model_name="recruitmenttag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="recruitment_tags", to="recruitments.tag"
            ),
        ),
        migrations.AlterModelTable(
            name="recruitmenttag",
            table="recruitments_recruitment_tag",
        ),
    ]
