# Generated by Django 5.2.7 on 2025-11-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitments", "0004_remove_recruitmenttag_unique_recruitment_tag_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[("APPROVED", "승인"), ("REVIEWING", "검토중"), ("PENDING", "대기"), ("REJECTED", "거절")],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
