# Generated by Django 5.2.7 on 2025-11-05 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitments", "0005_alter_application_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecruitmentSearchLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("keyword", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "공고 검색 로그",
                "verbose_name_plural": "공고 검색 로그 목록",
                "db_table": "recruitment_search_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="searchlog",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="recruitmentattachment",
            options={"verbose_name": "Recruitment Attachment", "verbose_name_plural": "Recruitment Attachments"},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Tag", "verbose_name_plural": "Tags"},
        ),
        migrations.AlterUniqueTogether(
            name="application",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="recruitmentimage",
            name="img_url",
            field=models.URLField(max_length=500),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.UniqueConstraint(
                fields=("recruitment", "user"), name="unique_application_per_user_per_recruitment"
            ),
        ),
        migrations.AlterModelTable(
            name="recruitmentattachment",
            table="recruitment_attachments",
        ),
        migrations.AlterModelTable(
            name="tag",
            table="tags",
        ),
        migrations.AddField(
            model_name="recruitmentsearchlog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recruitment_search_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="SearchLog",
        ),
        migrations.AddIndex(
            model_name="recruitmentsearchlog",
            index=models.Index(fields=["-created_at"], name="recruitment_created_0419a5_idx"),
        ),
        migrations.AddIndex(
            model_name="recruitmentsearchlog",
            index=models.Index(fields=["keyword"], name="recruitment_keyword_66deb9_idx"),
        ),
    ]
