# Generated by Django 5.2.7 on 2025-11-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitments", "0005_recruitmentsearchlog_remove_searchlog_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[("PENDING", "대기중"), ("APPROVED", "승인됨"), ("REJECTED", "거절됨"), ("CANCELED", "취소됨")],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
