# Generated by Django 5.2.7 on 2025-11-11 10:49

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitments", "0006_alter_application_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
