# Generated by Django 5.2.1 on 2025-10-15 09:08

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CrawledLecture",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("instructor", models.CharField(max_length=20)),
                ("average_rating", models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ("duration", models.SmallIntegerField()),
                (
                    "difficulty",
                    models.CharField(choices=[("EASY", "초급"), ("NORMAL", "중급"), ("HARD", "어려움")], max_length=10),
                ),
                ("description", models.TextField()),
                ("platform", models.CharField(choices=[("UDEMY", "Udemy"), ("INFLEARN", "Inflearn")], max_length=10)),
                ("original_price", models.BigIntegerField(default=0)),
                ("discount_price", models.BigIntegerField(default=0)),
                ("url_link", models.CharField(max_length=500)),
                ("thumbnail_img_url", models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                "db_table": "crawled_lectures",
                "ordering": ["-created_at"],
                "unique_together": {("platform", "title")},
            },
        ),
    ]
