# Generated by Django 5.2.1 on 2025-10-17 02:28

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "categories",
            },
        ),
        migrations.CreateModel(
            name="CrawledLecture",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("instructor", models.CharField(max_length=20)),
                ("average_rating", models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ("duration", models.SmallIntegerField()),
                (
                    "difficulty",
                    models.CharField(choices=[("EASY", "초급"), ("NORMAL", "중급"), ("HARD", "어려움")], max_length=10),
                ),
                ("description", models.TextField()),
                ("platform", models.CharField(choices=[("UDEMY", "Udemy"), ("INFLEARN", "Inflearn")], max_length=10)),
                ("original_price", models.BigIntegerField(default=0)),
                ("discount_price", models.BigIntegerField(default=0)),
                ("url_link", models.CharField(max_length=500)),
                ("thumbnail_img_url", models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                "db_table": "crawled_lectures",
                "ordering": ["-created_at"],
                "unique_together": {("platform", "title")},
            },
        ),
        migrations.CreateModel(
            name="CrawledLectureReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("5_OUT_OF_5_STARS", "5점"),
                            ("4_OUT_OF_5_STARS", "4점"),
                            ("3_OUT_OF_5_STARS", "3점"),
                            ("2_OUT_OF_5_STARS", "2점"),
                            ("1_OUT_OF_5_STARS", "1점"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="lecture.crawledlecture"
                    ),
                ),
            ],
            options={
                "db_table": "crawled_lecture_reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LectureCategory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "lecture_id", "category_id", blank=True, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecture_categories",
                        to="lecture.category",
                    ),
                ),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecture_categories",
                        to="lecture.crawledlecture",
                    ),
                ),
            ],
            options={
                "db_table": "lecture_categories",
            },
        ),
        migrations.CreateModel(
            name="LectureSearchLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("keyword", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecture_search_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "lecture_search_logs",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="UserPreferCategory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "user_id", "category_id", blank=True, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferred_by_users",
                        to="lecture.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prefer_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_prefer_categories",
            },
        ),
        migrations.CreateModel(
            name="LectureBookmark",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="lecture.crawledlecture",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecture_bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "lecture_bookmarks",
                "unique_together": {("user", "lecture")},
            },
        ),
    ]
