# Generated by Django 5.2.1 on 2025-10-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecture", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawledlecture",
            name="categories",
            field=models.ManyToManyField(
                related_name="crawled_lecture_categories", through="lecture.LectureCategory", to="lecture.category"
            ),
        ),
    ]
