# Generated by Django 5.2.7 on 2025-11-03 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lecture", "0002_crawledlecture_categories"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="crawledlecture",
            unique_together={("platform", "title", "instructor")},
        ),
    ]
