# Generated by Django 5.2.7 on 2025-11-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecture", "0003_alter_crawledlecture_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="crawledlecture",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="crawledlecture",
            name="external_id",
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="crawledlecturereview",
            name="external_id",
            field=models.BigIntegerField(),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="crawledlecture",
            unique_together={("platform", "external_id")},
        ),
        migrations.AlterUniqueTogether(
            name="crawledlecturereview",
            unique_together={("lecture", "external_id")},
        ),
    ]
