# Generated by Django 5.2.7 on 2025-11-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecture", "0003_alter_crawledlecture_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawledlecture",
            name="inflearn_course_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="crawledlecture",
            name="udemy_course_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="crawledlecturereview",
            name="inflearn_review_id",
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="crawledlecturereview",
            name="udemy_review_id",
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
