# Generated by Django 5.2.7 on 2025-11-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecture", "0006_alter_crawledlecture_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crawledlecture",
            name="external_id",
            field=models.BigIntegerField(),
        ),
    ]
