# Generated by Django 5.2.7 on 2025-11-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecture", "0007_alter_crawledlecture_external_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.CharField(default="temp_slug", max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
