# Generated by Django 5.2.7 on 2025-11-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecture", "0008_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.CharField(max_length=150),
        ),
    ]
