# Generated by Django 5.2.7 on 2025-11-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecture", "0009_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
