# Generated by Django 5.2.1 on 2025-10-17 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(editable=False, unique=True)),
                ("name", models.CharField(max_length=20)),
                ("introduction", models.CharField(max_length=100)),
                ("max_headcount", models.SmallIntegerField()),
                ("profile_img_url", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("PLANNED", "예정"), ("ACTIVE", "진행중"), ("CLOSED", "종료")], max_length=30
                    ),
                ),
            ],
            options={
                "db_table": "study_groups",
            },
        ),
        migrations.CreateModel(
            name="StudyNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("ai_summary", models.TextField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "study_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="notes", to="studies.studygroup"
                    ),
                ),
            ],
            options={
                "db_table": "study_notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudyNoteAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file_url", models.CharField(max_length=255)),
                ("file_name", models.CharField(max_length=255)),
                (
                    "study_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="studies.studynote"
                    ),
                ),
            ],
            options={
                "db_table": "study_note_attachments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudyNoteImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("img_url", models.CharField(max_length=255)),
                (
                    "study_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="images", to="studies.studynote"
                    ),
                ),
            ],
            options={
                "db_table": "study_note_images",
                "ordering": ["-created_at"],
            },
        ),
    ]
