# Generated by Django 5.2.1 on 2025-10-16 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.CharField(max_length=300, verbose_name="알림 내용,")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("APPLICATIONS_CREATED", "공고 지원 알림"),
                            ("APPLICATION_STATUS_CHANGED", "지원 승인/거절 알림"),
                            ("STUDY_MEMBER_JOINED", "스터디 그룹 신규 참여 알림"),
                            ("STUDY_REVIEW_REQUEST", "스터디 후기 작성 요청 알림"),
                            ("STUDY_SCHEDULE_UPCOMING", "예정 스케줄 알림"),
                            ("STUDY_SCHEDULE_TODAY", "금일 스케줄 알림"),
                            ("STUDY_RECORD_CREATED", "스터디 기록 작성 알림"),
                            ("SYSTEM", "시스템 알림"),
                            ("CUSTOM", "기타 사용자 정의 알림"),
                        ],
                        max_length=300,
                        verbose_name="알림 종류",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="읽음 여부")),
                ("back_url_link", models.CharField(blank=True, max_length=300, null=True, verbose_name="이동URL")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="유저",
                    ),
                ),
            ],
            options={
                "verbose_name": "알림",
                "verbose_name_plural": "알림 목록",
            },
        ),
    ]
