# Generated by Django 5.2.1 on 2025-10-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"verbose_name": "Notification", "verbose_name_plural": "Notifications"},
        ),
        migrations.AlterField(
            model_name="notification",
            name="back_url_link",
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name="이동 URL"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("APPLICATIONS_CREATED", "공고 지원 알림"),
                    ("APPLICATION_STATUS_APPROVAL", "지원 승인 알림"),
                    ("APPLICATION_STATUS_REJECTION", "지원 거절 알림"),
                    ("STUDY_MEMBER_JOINED", "스터디 그룹 신규 참여 알림"),
                    ("STUDY_REVIEW_REQUEST", "스터디 후기 작성 요청 알림"),
                    ("STUDY_SCHEDULE_UPCOMING", "예정 스케줄 알림"),
                    ("STUDY_SCHEDULE_TODAY", "금일 스케줄 알림"),
                    ("STUDY_RECORD_CREATED", "스터디 기록 작성 알림"),
                    ("SYSTEM", "시스템 알림"),
                    ("CUSTOM", "기타 사용자 정의 알림"),
                ],
                max_length=300,
                verbose_name="알림 종류",
            ),
        ),
    ]
