# Generated by Django 5.2.7 on 2025-11-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notification_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("APPLICATIONS_CREATED", "공고 지원 알림"),
                    ("APPLICATION_STATUS_APPROVAL", "지원 승인 알림"),
                    ("APPLICATION_STATUS_REJECTION", "지원 거절 알림"),
                    ("STUDY_MEMBER_JOINED", "스터디 그룹 신규 참여 알림"),
                    ("STUDY_REVIEW_REQUEST", "스터디 후기 작성 요청 알림"),
                    ("STUDY_SCHEDULE_UPCOMING", "예정 스케줄 알림"),
                    ("STUDY_SCHEDULE_TODAY", "금일 스케줄 알림"),
                    ("STUDY_RECORD_CREATED", "스터디 기록 작성 알림"),
                ],
                max_length=300,
                verbose_name="알림 종류",
            ),
        ),
    ]
